version: "3.9"

services:
  # сервис приложения FastAPI
  palette-app:
    build: .
    container_name: palette-app
    command: fastapi run ./daemon/daemon.py --reload --port=8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
